spring:
  application:
    name: meetingmind

  datasource:
    url: jdbc:postgresql://localhost:5432/meetingmind
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8081

app:
  file:
    upload-dir: uploads/meetings
    max-size: 10485760 # 10MB
    allowed-types:
      - application/pdf
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - text/plain
